#!/bin/sh

BASEDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
TMP_DIR="/tmp"
NORONHA_INST_FOLDER="/usr/share/noronha-dataops"
NORONHA_BRANCH="develop"
NORONHA_VENV="/usr/share/noronha-venv"

python3 -m venv ${NORONHA_VENV}
chmod 777 -R ${NORONHA_VENV}
source ${NORONHA_VENV}

pip3 install --upgrade requests
pip3 install six==1.10.0
pip3 install --upgrade setuptools
# pip3 install setuptools>=40.3.0

if [ "${SUDO_USER}" = "" ]; then
    EXEC_USER="${USER}"
else
    EXEC_USER="${SUDO_USER}"
fi
echo "Configuring Noronha for user ${EXEC_USER}"

ANACONDA_FILE=${TMP_DIR}/Anaconda3-2020.02-Linux-x86_64.sh
if [ -f "${ANACONDA_FILE}" ]; then
    echo "${ANACONDA_FILE} exist. Not Downloading it"
else 
    curl https://repo.anaconda.com/archive/Anaconda3-2020.02-Linux-x86_64.sh --output ${ANACONDA_FILE}
fi
sh ${ANACONDA_FILE} -b -p /home/${EXEC_USER}/anaconda


# DOCKER_INST_FILE=${TMP_DIR}/install_docker.sh
# if [ -f "${DOCKER_INST_FILE}" ]; then
#     echo "${DOCKER_INST_FILE} exist. Not Downloading it"
# else 
#     curl -fsSL https://get.docker.com -o ${DOCKER_INST_FILE}
# fi
# sh ${DOCKER_INST_FILE}

# /usr/sbin/groupadd docker
/usr/sbin/usermod -aG docker ${EXEC_USER}

docker swarm init

pip3 install ${NORONHA_INST_FOLDER}

# nha get_me_started

# chown -R ${EXEC_USER} /home/${EXEC_USER}/.nha
chown -R ${EXEC_USER} /home/${EXEC_USER}/anaconda

docker build -f "${NORONHA_INST_FOLDER}/Dockerfile" -t "noronha.everis.ai/noronha:${NORONHA_BRANCH}" ${NORONHA_INST_FOLDER}

echo "export NORONHA_VENV=${NORONHA_VENV}" >> /etc/bash.bashrc

echo "You must reboot this machine to the changes take effect"